global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['kafka1:9092', 'kafka2:9093', 'kafka3:9094']

